name: denonceur
description: "Une application qui permet aux personnes harcelÃ©es de dÃ©noncer ce qu'elles subissent en tout anonymat."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-120.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  qr_flutter: ^4.1.0
  lucide_icons: ^0.257.0
  provider: ^6.1.1
  qr_code_scanner: ^1.0.1
  http: ^1.1.0
  expandable_text: 2.3.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env